[package]
name = "megamerge"
version = "0.2.0"
edition = "2018"

[lib]
name = "megamerge"
crate-type = ["cdylib"]

[dependencies]
pyo3    = { version = "0.15.1", features = ["extension-module"] }
numpy   = { version = "0.15" }
ndarray = { version = "0.15", features=["rayon"] }